### ISSUE TITLE
Parse File with MIPS Code

### ISSUE THREAD

**Issue by PandaEden** [EDEN786/MIPS-Teaching-Tool#1]
Objective : [Support for a subset of MIPS Instructions](https://app.gitkraken.com/glo/card/9391a3043dae487e8c450ccffe12bd8a)

- [x] Define Parsing requirements
- [x] Define Subset supported MIPS instructions
- [x] Write code for parsing given parameters, for a given file 'FileInput.s' in the same directory
- [x] Arrange the Parsed information ready prepared for emulation
- [x] Write Tests

**Comment by PandaEden** [comment]
ref: https://www.dsi.unive.it/~gasparetto/materials/MIPS_Instruction_Set.pdf
https://fog.ccsf.edu/~gboyd/cs270/online/mipsI/mips_basics.html
https://en.wikibooks.org/wiki/MIPS_Assembly/Instruction_Formats

\# comment | . ignore past a "#"
tag: | text

# Registers
|  Syntax | Meaning      |
| -------- | -------------- |
| **$rd**    | _Destination_  |
| **$rs**    | _Source_       |
| **$rt**    | _Target/Third_ |
| **imm**      | _Immediate_    |
| **off**      | _Offset_ |
| **[ label ]:** | _Jump Label_ |
| -------- | -------------- |
| **$zero**   |  constant 0  |
| **t#**   |  temporaries #0-9 |
| **s#**   |  saved temporaries #0-7 |
| **a#**   |  argument registers #0-3 |

# Arithmetic
**add** $rd, $rs, $rt    ' R Type . Add
**sub** $rd, $rs, $rt    ' R Type . Subtract
**addi** $rt, $rs, _imm_    ' I Type . Add Immediate 

# Load/Store 
**lw** $rd, _off_($rs)    'I Type . Load Word ( 16bits )
**sw** $rt, _off_($rs)    'I Type . Store Word

# Jump
**j** [ label ]    'J Type
**jal** [ label ]    'J Type, saves address PC+8 (or nPC+4) into $ra.  the +8 is due to Branch Delay Slot after the jump instruction.

**Comment by PandaEden** [comment]
Parser will run line by line.
Blank space before/between any characters will be ignored. 
  and if the first character on a line is a number sign '#', the entire line will be ignored

the operation should be white space separated [" "] from the first operand.
 subsequent operands must be comma and white space separated [", "].

currently operating with signed Immediate values .    value must be in the range of -(2^15) to (2^15)-1
offset immediate + value $rs must be a multiple of 4, or will cause an addressing trap

**Comment by EDEN786** [comment]
Usually in MIPS the address would be calculated. To simplify operation,
 labels will be stored with the index of the instruction/data in the Instruction_ArrayList

changing the index of the ArrayList is functionally equivelent to updating the Program counter.
  i.e,  PC=PC+4 is equivalent to Index++; (I = i+1);

Where usually the address would be calculated and PC = address. 
We can load the instruction index to the Index integer in the execution for_loop.

**Comment by PandaEden** [comment]
Parsing for .data / .code segments,
  and storing indexes of Labels to be used by Jump and Load/Store instructions.

**Comment by PandaEden** [comment]
Usually in MIPS the address would be calculated. To simplify operation,
labels will be stored with the index of the instruction/data in the Instruction_ArrayList

changing the index of the ArrayList is functionally equivalent to updating the Program counter.
i.e, PC=PC+4 is equivalent to Index++; (I = i+1);

Where usually the address would be calculated and PC = address.
We can load the instruction index to the Index integer in the execution for_loop.

**Comment by PandaEden** [comment]
Ref: [http://pages.cs.wisc.edu/~smoler/cs354/onyourown/arrays.html](http://pages.cs.wisc.edu/~smoler/cs354/onyourown/arrays.html)
To simplify initial version, will only support data types
``` .word, .asciiz.```

```
	.word represents a 32Bit Integer.
	.asciiz represents a String.
	
	.word <int> #Single integer value (Offset =0)
	.word <int>,<int>,<int> #Array of Integer Values, offset needs to be multiple of 4
	.asciiz "<string>" #.asciiz requires quotation marks
	.word <val>:<N> #Array #Creates empty array of N elements (elements will be initialized to value <val>)
```

The parser will have two modes, reading ".data" or ".text" on a line will switch it between these modes.
Lines with no code will not be parsed and skipped.

The parser will run in 2 lengths,
First it will scan for labels, if it is in Data mode, the labels read will be stored as a "data label"
   if it is in a Text mode,  the label read will be stored as a "text label"

the default mode will be Text mode, if a .data segment is not specified, it will assume all labels are "text labels"

The Offset of a lw/sw needs to match a compiled 'data label'
The label in a J_type instruction needs to match a compiled 'text label'

**Comment by PandaEden** [comment]
based on MARS.

  Instruction Address start from 0x00400000 (heap)
  Data Addresses start from 0x10010000 (.data)
  ¬External Data (which won't be supported) start from 0x10000000 (.extern)

![image.png](https://app.gitkraken.com/api/glo/boards/5fa476650d832b0011253c14/attachments/5ffca6e61c54ef001162e29c)

for Jump instructions, the label is assembled into the address of the next instruction (ignores blank lines/ lines that are only a label/ comment)
![image.png](https://app.gitkraken.com/api/glo/boards/5fa476650d832b0011253c14/attachments/5ffcb06c6f04050011740049)
![image.png](https://app.gitkraken.com/api/glo/boards/5fa476650d832b0011253c14/attachments/5ffcb0721c54ef001162e544)

Branch instructions assemble the immediate into the offset from the address of the next instruction (since program counter is always incremented PC+4)

example "blez $23, -25"
``` 
 current instruction address: (_0x:00400060_)
  next instruction address: (_0x:00400064_) (PC+4)
  target instruction address: (_0x:00400000_)

 offset -25.    * 4 is -100.   in Hexadecimal this is 0x64
 *0x:00400064 - 0x:64 => 0x:00400000*
```
