### ISSUE TITLE
QOL/Feature: instead of exiting, prompt the user to provide an input file

### ISSUE THREAD

**Issue by jccmontoya** [EDEN786/MIPS-Teaching-Tool#34]
I've tried to run the program with no input file and no default file and it crashes.

**Comment by PandaEden** [comment]
Running the command:
`java -jar MTT-1.0.jar`

Expected Output (Ubuntu - WSL)
![image](https://user-images.githubusercontent.com/23419505/112899997-bfcbb200-90da-11eb-9553-2405103209e4.png)

On-Windows:
![image](https://user-images.githubusercontent.com/23419505/112900129-ef7aba00-90da-11eb-98a2-15fc8671af9c.png)

Please check the Java version, It could be (on windows) the environment variables (PATH) is not set to include the right version:
type:
$ `java --version`

It needs to be a java version of at least 11. 

Lastly if none of that works, please provide a screenshot/ copy of any error message from it crashing.

**Comment by jccmontoya** [comment]
My bad, I got the first result as I run on Mac and I thought it was
crashing.

José Carlos

**Comment by PandaEden** [comment]
Ok, this is intended behaviour then.
It provides a warning for _no input file_.
Then an error for the _default file_ also not existing.

If you think it could be more clear let me know.

**Comment by jccmontoya** [comment]
It's just a detail, but instead of the red error message, I would try to be
more user friendly. Perhaps a message informing that there is no input file
would be enough. In fact, the application could, instead of exiting, prompt
the user to provide an input file.

José Carlos
